/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginhome;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class registerframe extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs  = null;
    public registerframe() {
        initComponents();
        getContentPane().setBackground(Color.yellow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        firstnametext = new javax.swing.JTextField();
        lastnametext = new javax.swing.JTextField();
        addresstext = new javax.swing.JTextField();
        gmailtext = new javax.swing.JTextField();
        contactnotext = new javax.swing.JTextField();
        registerbutton = new javax.swing.JButton();
        passwordlabel = new javax.swing.JLabel();
        deletebutton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        resetbutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        password1text = new javax.swing.JPasswordField();
        confirm1text = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));
        setForeground(new java.awt.Color(153, 0, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("PIZZA CORNER");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Add your details here!!!");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("First Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Address");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Gmail");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Contact nomber");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Password");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Confirm Password");

        registerbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        registerbutton.setText("REGISTER");
        registerbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerbuttonMouseClicked(evt);
            }
        });
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });

        passwordlabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        deletebutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deletebutton.setText("DELETE");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("YOU CAN DELETE YOUR ACCOUNT FROM YOUR GMAIL AND YOUR ACCOUNT PASSWORD!!!");

        resetbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resetbutton.setText("RESET");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });

        updatebutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updatebutton.setText("UPDATE");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("YOU CAN UPDATE YOUR ACCOUNT FROM YOUR GMAIL AND YOUR ACCOUNT USERNAME!!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(contactnotext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                                    .addComponent(firstnametext, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastnametext, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addresstext, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gmailtext, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password1text, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirm1text)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(passwordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(registerbutton)
                                .addGap(18, 18, 18)
                                .addComponent(deletebutton)
                                .addGap(18, 18, 18)
                                .addComponent(resetbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(updatebutton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(firstnametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lastnametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addresstext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(gmailtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(contactnotext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(password1text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(confirm1text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerbutton)
                    .addComponent(deletebutton)
                    .addComponent(resetbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(passwordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbuttonMouseClicked
       
       
    }//GEN-LAST:event_registerbuttonMouseClicked

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed
       //JOptionPane.showMessageDialog(this,firstnametext.getText());
       //JOptionPane.showMessageDialog(this,lastnametext.getText());
       String firstname=firstnametext.getText();
       String lastname=lastnametext.getText();
       String address=addresstext.getText();
       String gmail=gmailtext.getText();
       String contactno=contactnotext.getText();
       String password=password1text.getText();
       String confirmpassword=confirm1text.getText();
       
        
       if(password.length() < 8) {
           passwordlabel.setText("Pasword must have atleast 8 characters.");
           return;
       }else if (password.length() > 15) {
           passwordlabel.setText("Pasword must have atmost 15 characters.");
           return;
       }else if (!password.matches("(.*[A-Z].*)")) {
           passwordlabel.setText("Pasword must have atleast 1 upercase letter.");
           return;
       }else if (!password.matches("(.*[a-z].*)")) {
           passwordlabel.setText("Pasword must have atleast 1 lowercase letter.");
           return;
       }else if (!password.matches("(.*[0-9].*)")) {
           passwordlabel.setText("Pasword must have atleast 1 number.");
           return;
       }else if (!password.matches("(.*[@#$%!].*)")) {
           passwordlabel.setText("Pasword must have atleast 1 special character from @, #, $, %, !.");
           return;
       
       }
        
       passwordlabel.setText("Safe Password.");
       //this.setVisible(false);
       //new registerdetailframe().setVisible(true);
       try{
            String sql = "INSERT INTO customerjavanew"
                    +"(Firstname, Lastname, Address, Gmail, Contactno, Password)"
                    +" VALUES (?,?,?,?,?,?)";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/customerjavanew","root","");
            pst = (PreparedStatement) con.clientPrepareStatement(sql);
            pst.setString(1,firstnametext.getText());
            pst.setString(2,lastnametext.getText());
            pst.setString(3,addresstext.getText());
            pst.setString(4,gmailtext.getText());
            pst.setString(5,contactnotext.getText());
            pst.setString(6,password1text.getText());
            pst.executeUpdate();
            //DefaultTableModel model = (DefaultTableModel) detailtabel.getModel();
            //model.addRow(new Object[]{firstnametext.getText(),lastnametext.getText(),addresstext.getText(),gmailtext.getText(),contactnotext.getText(),passwordtext.getText()});
            JOptionPane.showMessageDialog(null,"Inserted Successfully");
            
            registerdetailframe rd = new registerdetailframe();
            rd.setVisible(true);
                
            rd.welcomelabel.setText("WELCOME  "+firstname+"  !!!");
            this.setVisible(false);
       }
       catch(SQLException | HeadlessException ex){
           JOptionPane.showMessageDialog(null,ex);
       }
    }//GEN-LAST:event_registerbuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        try{
            String sql = "DELETE FROM customerjavanew WHERE Gmail =? AND Password = ?";
                    
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/customerjavanew","root","");
            pst = (PreparedStatement) con.clientPrepareStatement(sql);
            pst.setString(1,gmailtext.getText());
            pst.setString(2,password1text.getText());
            //pst.setString(3,addresstext.getText());
            //pst.setString(1,gmailtext.getText());
            //pst.setString(5,contactnotext.getText());
            //pst.setString(6,passwordtext.getText());
            pst.executeUpdate();
            //DefaultTableModel model = (DefaultTableModel) detailtabel.getModel();
            //int SelectedRowIndex = detailtabel.getSelectedRow();
            //model.removeRow(0);
            JOptionPane.showMessageDialog(null,"Delete Successfully");
            new homeframe().setVisible(true);
            this.setVisible(false);
       }
       catch(SQLException | HeadlessException ex){
           JOptionPane.showMessageDialog(null,ex);
       }
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
       firstnametext.setText(null);
       lastnametext.setText(null);
       addresstext.setText(null);
       gmailtext.setText(null);
       contactnotext.setText(null);
       password1text.setText(null);
       confirm1text.setText(null);
       //DefaultTableModel model = (DefaultTableModel) detailtabel.getModel();
       //int SelectedRowIndex = detailtabel.getSelectedRow();
       //model.removeRow(1);
       
       
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        
       try{
            String firstname=firstnametext.getText();
            String sql = "UPDATE customerjavanew SET Lastname=?,Address=?,Contactno=?,Password=? WHERE Firstname=? AND Gmail=?";
                    
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/customerjavanew","root","");
            pst = (PreparedStatement) con.clientPrepareStatement(sql);
            pst.setString(5,firstnametext.getText());
            pst.setString(1,lastnametext.getText());
            pst.setString(2,addresstext.getText());
            pst.setString(6,gmailtext.getText());
            pst.setString(3,contactnotext.getText());
            pst.setString(4,password1text.getText());
            pst.executeUpdate();
            //DefaultTableModel model = (DefaultTableModel) detailtabel.getModel();
            //model.addRow(new Object[]{firstnametext.getText(),lastnametext.getText(),addresstext.getText(),gmailtext.getText(),contactnotext.getText(),passwordtext.getText()});
            
            JOptionPane.showMessageDialog(null,"Updated Successfully");
            //String firstname=firstnametext.getText();
            registerdetailframe rd = new registerdetailframe();
            rd.setVisible(true);
                
            rd.welcomelabel.setText("WELCOME  "+firstname+"  !!!");
            this.setVisible(false);
       }
       catch(SQLException | HeadlessException ex){
           JOptionPane.showMessageDialog(null,ex);
       } 
    }//GEN-LAST:event_updatebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresstext;
    private javax.swing.JPasswordField confirm1text;
    private javax.swing.JTextField contactnotext;
    private javax.swing.JButton deletebutton;
    private javax.swing.JTextField firstnametext;
    private javax.swing.JTextField gmailtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastnametext;
    private javax.swing.JPasswordField password1text;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JButton registerbutton;
    private javax.swing.JButton resetbutton;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables

   
}
